/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.2/userguide/multi_project_builds.html
 */


rootProject.name = "task"
include("app", "client-module", "preparation-document-module", "materials-module", "client-module",
    "preparation-document-module", "materials-module", "printer-module", "report-module", "cutter-module",
    "order-module", "envelope-module", "packaging-module", "transportation-module")
include("app-module")
